# Generated by Django 5.2.5 on 2025-08-17 11:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Allowance Name')),
                ('amount', models.FloatField(null=True, verbose_name='Amount')),
                ('is_fixed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Allowance Type',
                'verbose_name_plural': 'Allowance Types',
                'db_table': 'allowance_type',
            },
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Shift Type Name')),
                ('coefficient', models.FloatField(verbose_name='Coefficient')),
            ],
            options={
                'verbose_name': 'Shift Type',
                'verbose_name_plural': 'Shift Types',
                'db_table': 'shift_type',
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Work Coefficient Type Name')),
                ('coefficient', models.FloatField(verbose_name='Coefficient')),
            ],
            options={
                'verbose_name': 'Work Type',
                'verbose_name_plural': 'Work Types',
                'db_table': 'work_type',
            },
        ),
        migrations.CreateModel(
            name='CommendationDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='Content')),
                ('date', models.DateField(verbose_name='Date')),
                ('record_type', models.CharField(choices=[('Commendation', 'Commendation'), ('Discipline', 'Discipline')], default='Commendation', max_length=20)),
                ('amount', models.FloatField(default=0.0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commendations_disciplines', to='employee.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Commendation/Discipline',
                'verbose_name_plural': 'Commendations/Disciplines',
                'db_table': 'commendation_discipline',
            },
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('month', models.IntegerField(null=True, verbose_name='Month')),
                ('year', models.IntegerField(null=True, verbose_name='Year')),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advances', to='employee.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Salary Advance',
                'verbose_name_plural': 'Salary Advances',
                'db_table': 'salary_advance',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employee.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('month', models.IntegerField(verbose_name='Month')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('time_in', models.TimeField(blank=True, null=True, verbose_name='Time In')),
                ('time_out', models.TimeField(blank=True, null=True, verbose_name='Time Out')),
                ('hours', models.FloatField(verbose_name='Hours')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtimes', to='employee.employee', verbose_name='Employee')),
                ('shift_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime', to='timesheet.shifttype', verbose_name='ShiftType')),
            ],
            options={
                'verbose_name': 'Overtime',
                'verbose_name_plural': 'Overtime Records',
                'db_table': 'overtime',
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(verbose_name='Year')),
                ('month', models.IntegerField(verbose_name='Month')),
                ('date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Date')),
                ('time_in', models.TimeField(blank=True, null=True, verbose_name='Time In')),
                ('time_out', models.TimeField(blank=True, null=True, verbose_name='Time Out')),
                ('extra_break_minutes', models.IntegerField(default=0, verbose_name='Extra Break Minutes')),
                ('lunch_break', models.IntegerField(default=1)),
                ('total_working_hours', models.FloatField(default=0.0)),
                ('work_coefficient', models.FloatField(default=0.0)),
                ('is_ordinary', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('late_minutes', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='employee.employee', verbose_name='Employee')),
                ('work_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet', to='timesheet.worktype', verbose_name='WorkType')),
            ],
            options={
                'verbose_name': 'Timesheet',
                'verbose_name_plural': 'Timesheets',
                'db_table': 'timesheet',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
