# Generated by Django 5.2.4 on 2025-07-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commendationdiscipline',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='total_working_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
