# Generated by Django 5.2.4 on 2025-07-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_commendationdiscipline_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='lunch_break',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
