# Generated by Django 5.2.4 on 2025-07-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_timesheet_lunch_break_alter_timesheet_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commendationdiscipline',
            name='code',
        ),
    ]
