# Generated by Django 5.2.4 on 2025-07-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_base_salary_employee_salary_grade'),
        ('timesheet', '0005_leaverequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={},
        ),
        migrations.AddField(
            model_name='overtime',
            name='time_in',
            field=models.TimeField(blank=True, null=True, verbose_name='Time In'),
        ),
        migrations.AddField(
            model_name='overtime',
            name='time_out',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Out'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='work_coefficient',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterUniqueTogether(
            name='leaverequest',
            unique_together={('employee', 'date')},
        ),
    ]
