# Generated by Django 5.2.4 on 2025-07-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0006_alter_leaverequest_options_overtime_time_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryadvance',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='allowancetype',
            name='amount',
            field=models.FloatField(null=True, verbose_name='Amount'),
        ),
    ]
