# Generated by Django 5.2.4 on 2025-07-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0007_salaryadvance_amount_alter_allowancetype_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryadvance',
            name='month',
            field=models.IntegerField(null=True, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='salaryadvance',
            name='year',
            field=models.IntegerField(null=True, verbose_name='Year'),
        ),
    ]
