# Generated by Django 5.2.4 on 2025-07-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0008_alter_salaryadvance_month_alter_salaryadvance_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancetype',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
