# Generated by Django 5.2.4 on 2025-08-11 07:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0009_allowancetype_is_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Date'),
        ),
    ]
