# Generated by Django 5.2.5 on 2025-08-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0010_alter_timesheet_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
