# Generated by Django 5.2.5 on 2025-08-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0011_timesheet_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='is_ordinary',
            field=models.BooleanField(default=True),
        ),
    ]
