# Generated by Django 5.2.5 on 2025-08-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0012_timesheet_is_ordinary'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='late_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
