name: Deploy Django to Render

on:
  push:
    branches:
      - main   # chạy khi push vào nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Bước test (tuỳ chọn, bạn có thể bỏ nếu chưa cần)
      # - name: Run Django tests
      #   run: |
      #     python manage.py test || echo "Tests failed but continue"

      # Trigger Render Deploy Hook
      - name: Trigger Render Deploy
        run: |
          curl "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
