# Generated by Django 5.2.4 on 2025-07-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workstandard',
            options={'ordering': ['standard_work_number']},
        ),
    ]
