# Generated by Django 5.2.4 on 2025-07-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_payroll_is_locked_payrollhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='standard_work_number',
            field=models.IntegerField(default=0),
        ),
    ]
