# Generated by Django 5.2.4 on 2025-07-10 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='face_embedding', serialize=False, to='employee.employee', verbose_name='employee.Employee')),
                ('image_path', models.CharField(max_length=255, verbose_name='Image Path')),
                ('embedding', models.BinaryField(verbose_name='Embedding')),
            ],
            options={
                'verbose_name': 'Face Embedding',
                'verbose_name_plural': 'Face Embeddings',
                'db_table': 'face_embedding',
            },
        ),
        migrations.CreateModel(
            name='FaceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('is_matched', models.BooleanField(verbose_name='Is Matched')),
                ('image_path', models.CharField(max_length=255, verbose_name='Image Path')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='Confidence Score')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_logs', to='employee.employee', verbose_name='employee.Employee')),
            ],
            options={
                'verbose_name': 'Face Log',
                'verbose_name_plural': 'Face Logs',
                'db_table': 'face_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
