# Generated by Django 5.2.5 on 2025-08-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facelog',
            name='timestamp',
            field=models.TimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='facerecognitionfailure',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='facetrackingsession',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='facetrackingsession',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facetrackingsession',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='facetrainingimage',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
