# Generated by Django 5.2.5 on 2025-08-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0002_alter_facelog_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facetrackingsession',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='facelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
    ]
