# Generated by Django 5.2.5 on 2025-08-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0003_facetrackingsession_date_alter_facelog_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facetrackingsession',
            name='date',
        ),
        migrations.AlterField(
            model_name='facerecognitionfailure',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='facetrackingsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='facetrackingsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facetrackingsession',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='facetrainingimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
