# Generated by Django 5.2.5 on 2025-08-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0004_remove_facetrackingsession_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facetrainingimage',
            name='embedding',
            field=models.BinaryField(null=True, verbose_name='Embedding'),
        ),
    ]
