# Generated by Django 5.2.4 on 2025-07-10 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeallowance',
            name='allowance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_allowances', to='timesheet.allowancetype', verbose_name='Allowance Type'),
        ),
        migrations.AddField(
            model_name='employeeallowance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_allowances', to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employee.position', verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employee.qualification', verbose_name='Qualification'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeallowance',
            unique_together={('employee', 'allowance_type', 'date')},
        ),
    ]
