# Generated by Django 5.2.4 on 2025-07-15 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_department_description_division_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='employee.department', verbose_name='Department'),
        ),
    ]
