# Generated by Django 5.2.4 on 2025-07-20 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_options_and_more'),
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='base_salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='salary.basesalary', verbose_name='BaseSalary'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='salary.salarygrade', verbose_name='Salary Grade'),
        ),
    ]
