# Generated by Django 5.2.4 on 2025-07-27 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_base_salary_employee_salary_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeallowance',
            name='amount',
            field=models.FloatField(null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='employeeallowance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 27, 14, 44, 5, 987903), verbose_name='Date'),
        ),
    ]
