# Generated by Django 5.2.4 on 2025-07-28 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employeeallowance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeallowance',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
