# Generated by Django 5.2.5 on 2025-08-11 09:34

import django_mysql.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklocation',
            name='status',
            field=django_mysql.models.EnumField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending'),
        ),
    ]
