# Generated by Django 5.2.5 on 2025-08-21 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklocation',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Date'),
        ),
    ]
