# Generated by Django 5.2.5 on 2025-08-11 10:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employeeallowance_date'),
        ('worklocation', '0002_worklocation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklocation',
            name='date',
            field=models.DateField(default=datetime.datetime.now, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='worklocation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_locations', to='employee.employee', verbose_name='Employee'),
        ),
    ]
