# Generated by Django 5.2.5 on 2025-08-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklocation', '0003_alter_worklocation_date_alter_worklocation_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
