name: Build & Deploy to Render

on:
  push:
    branches:
      - main  # Chạy khi push vào main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3️⃣ Cache pip packages để build nhanh hơn
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      # 4️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker buildx build \
            --tag hrmbackend:latest \
            --load \
            ./HRMproject

      # 5️⃣ Deploy lên Render
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "https://api.render.com/deploy/srv-xxxxxxxxxxxx" \
          -H "Authorization: Bearer $RENDER_API_KEY"
